### ISSUE TITLE
New version for rugged bump?

### ISSUE THREAD

**Issue by emilong** [kevinjalbert/pronto-stylelint#11]
Looks like dependabot updated the range on rugged in https://github.com/kevinjalbert/pronto-stylelint/pull/10, but it appears the latest (?) version, [0.10.0](https://rubygems.org/gems/pronto-stylelint), does not include this bump?

Would it be possible to release a new version incorporating this change? Thanks!

**Comment by kevinjalbert** [comment]
I've pushed a new version https://github.com/kevinjalbert/pronto-stylelint/releases/tag/v0.10.1 to [rubygems](https://rubygems.org/gems/pronto-stylelint/versions/0.10.1).

This should contain the changes you are looking for.
