### ISSUE TITLE
Depends on older version of pronto

### ISSUE THREAD

**Issue by mvz** [kevinjalbert/pronto-stylelint#3]
Hi,

`pronto-stylelint` depends on pronto `~> 0.7.0`, which causes problems when it is installed alongside the newer 0.8.x versions of pronto:

```
$ pronto run
/home/matijs/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:2288:in  `raise_if_conflicts': Unable to activate pronto-stylelint-0.7.1, because pronto-0.8.2 conflicts with pronto (~> 0.7.0) (Gem::ConflictError)
[...]
```

Please consider updating to the current pronto 0.8.x.

**Comment by kevinjalbert** [comment]
I will get around to updating this tonight. Thanks for bringing it up to my attention 👍

**Comment by kevinjalbert** [comment]
@mvz a new version (0.8.2) should be up on rubygems!

**Comment by mvz** [comment]
Thanks!
